### PR TITLE
update default font to lato

### PR DESCRIPTION
**Pull request by yimenglovesai**
https://github.com/Loopring/loopr-ios/issues/65

### CODE REVIEW

**Comment by xiaowheat** [comment]
@yimenglovesai Could you add some screenshots for DIN font and Lato Font?

**Comment by yimenglovesai** [comment]
Lato: 
screen shot 2018-04-22 at 9 57 27 pm
screen shot 2018-04-22 at 9 57 38 pm

**Comment by yimenglovesai** [comment]
DIN: 
screen shot 2018-04-22 at 9 59 57 pm
screen shot 2018-04-22 at 10 00 07 pm

**Comment by xiaowheat** [comment]
Let's use Lato first. The size of Lato and OpenSans are the same. We can switch to OpenSans very early. The size of DIN is smaller.

**Pull request merged**
